import "../pages/index.css"
import "../../node_modules/bootstrap/dist/js/bootstrap.min.js"
import "../../src/vendor/font-awesome/js/all.js"
import "../../node_modules/jquery/dist/jquery.slim.js"
import "../../src/vendor/magnific-popup/dist/jquery.magnific-popup.min.js"
import "../../src/scripts/index.js"